### PR TITLE
Increased required python version to 3.5

### PR DESCRIPTION
**Pull request by Arthasasyan**

### CODE REVIEW

**Comment by rodionos** [comment]
@annstriganova - Please review for completeness.

**Comment by annstriganova** [comment]
@rodionos, should the year in the LICENSE be updated?

**Comment by rodionos** [comment]
We can keep it license year as is, 2018.

**Comment by rodionos** [comment]
@Arthasasyan - After review from @annstriganova (if OK), change PR labels to 'done'

**Pull request merged**
