### PR TITLE
Changed HST timezone to GMT

### PR DESCRIPTION
**Pull request by Arthasasyan**

### CODE REVIEW

**Comment by rodionos** [comment]
Pick another timezone - GMT has no offset and no summer time.

**Comment by Arthasasyan** [comment]
Is Europe/Moscow suitable?

**Comment by rodionos** [comment]
Pick a timezone that has both non-zero offset and summer time. Moscow time zone has no DST offset.

**Comment by Arthasasyan** [comment]
DST offset is enabled for Eastern European Time, e.g. Europe/Helsinki
I other tests there are mentions of Asia/Yekaterinburg timezone that does not have DST offset. Should these mentions be changed to Europe/Helsinki?

**Comment by Arthasasyan** [comment]
DST is enabled for America/Havana

**Pull request merged**
